title: 오정규 Blog
email: hhh2123623@gmail.com

github_username:  OhJeonggyu
facebook_username: JeonggyuOh1990

markdown: kramdown
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript", "with_toc_data", "tables"]

highlighter: rouge

permalink: pretty

safe: true
lsi: true

gems:
  - jekyll-redirect-from
  - jemoji